name: bnf-pytest
permissions:
  contents: read

on:
  - pull_request
  - push

env:
  PYTHON_LATEST_VERSION: '3.14'

jobs:
  bnf-pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - uses: actions/checkout@v6

      - uses: StoneMoe/setup-antlr4@v4

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: dependencies
        working-directory: bnf
        run: uv sync --locked --extra dev

      - name: pytest
        working-directory: bnf
        run: uv run pytest

  build:
    runs-on: ubuntu-latest
    needs: bnf-pytest

    if: "github.event_name == 'push' && startsWith(github.ref, 'refs/tags')"

    steps:
      - uses: actions/checkout@v6

      - name: recovery tag information
        run: git fetch --tags --force

      - uses: StoneMoe/setup-antlr4@v4

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_LATEST_VERSION }}

      - name: build
        working-directory: bnf
        run: |
          pip install build
          python -m build

      - uses: actions/upload-artifact@v5
        with:
          name: dist
          path: bnf/dist/*

  upload:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: pypi-bnf
      url: https://pypi.org/project/apyds-bnf
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v6
        with:
          name: dist
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
